logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.security: DEBUG
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.transaction: DEBUG


spring:
  profiles:
    active: localDB
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  datasource:
    tomcat:
      jdbc-interceptors: "org.apache.tomcat.jdbc.pool.interceptor.ConnectionState;org.apache.tomcat.jdbc.pool.interceptor.StatementFinalizer"
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
      group-id: consumer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    admin:
      client-id: adminclient-1
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
      properties:
        zookeeper.connect: localhost:2181
#      interceptor:
#        classes:
#          org.apache.kafka.clients.producer.internals.ProducerInterceptors
      topics:
        - name: message
          partitions: 3
          replicas: 1
        - name: transaction
          partitions: 2
          replicas: 1
        - name: topic3
          partitions: 4
          replicas: 2
        - name: topic4
          partitions: 1
          replicas: 1
        - name: topic5
          partitions: 3
          replicas: 2

server:
  port: 9001

---

# Настройки для профиля localDB

spring:
  config:
    activate:
      on-profile: localDB
  h2:
    console:
      enabled: true
      settings:
        trace: on
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: false
    show-sql: true
    hibernate:
      ddl-auto: create-drop