logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.springframework.jdbc.core.JdbcTemplate: debug
    org.springframework.transaction: debug
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      springframework:
        security: DEBUG
spring:
  profiles:
    active: localDB
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  datasource:
    tomcat:
      jdbc-interceptors: org.apache.tomcat.jdbc.pool.interceptor.ConnectionState;org.apache.tomcat.jdbc.pool.interceptor.StatementFinalizer

server:
  port: 9000
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

---

# Настройки для профиля localDB

spring:
  config:
    activate:
      on-profile: localDB
  h2:
    console:
      enabled: true
      settings:
        trace: on
  sql:
    init:
      mode: always
#        script-locations: classpath:data.sql
#      data-locations: classpath:data-h2.sql
#      schema-locations: classpath:schema-h2.sql
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: false
    show-sql: true
    hibernate:
      ddl-auto: create-drop

---

# Настройки для профиля prod
# Нужно указать url, password, user для дб
---
#spring:
#  config:
#    activate:
#      on-profile: prod
#      sql:
#        init:
#          mode: always
#          script-locations: classpath:data.sql # Указываем путь к файлу data.sql в ресурсах
#  datasource:
#    url: jdbc:postgresql://hattie.db.elephantsql.com:5432/kksoceqt
#    username: kksoceqt
#    password: SuewuMYeqUD8rVgmtQlrpvieFCrDVe3A
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    defer-datasource-initialization: true
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    show-sql: true
#    hibernate:
#      ddl-auto: update
